set_charging_current:
  target:
    entity:
      domain: number
      integration: daze
  fields:
    current:
      required: true
      selector:
        number:
          min: 6000
          max: 32000
          step: 100
          unit_of_measurement: "mA"
      description: "Maximum charging current in milliamps (mA)."

start_charge:
  target:
    entity:
      domain: switch
      integration: daze

stop_charge:
  target:
    entity:
      domain: switch
      integration: daze
