name: Validate

on:
  push:
    branches: [development]

jobs:
  validate:
    name: Validate Code
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: "Set up Python"
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version-file: "pyproject.toml"

      - name: Install uv
        uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9 # v9.0.0

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Ruff Linting
        run: |
          uv pip install ruff
          uv run ruff check custom_components/daze/

      - name: Run Type Checking
        run: |
          uv pip install pyright homeassistant-stubs
          uv run pyright custom_components/daze/

      - name: Run tests
        run: uv run pytest tests/

  hassfest:
    name: Hassfest validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run hassfest
        uses: home-assistant/actions/hassfest@master

  hacs:
    name: HACS validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run HACS validation
        uses: hacs/action@main
        with:
          category: integration
